/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javabasicexamples;

/**
 *
 * @author dennix
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PaneEjemplo = new org.jdesktop.swingx.JXTitledPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDemo = new javax.swing.JToggleButton();
        btnCodigo = new javax.swing.JToggleButton();
        panelDemo = new org.jdesktop.swingx.JXPanel();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PaneEjemplo.setTitle("Concatenar cadenas");
        PaneEjemplo.getContentContainer().setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btnDemo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabasicexamples/ui/images/light.png"))); // NOI18N
        btnDemo.setMnemonic('D');
        btnDemo.setToolTipText("Demo");
        btnDemo.setFocusable(false);
        btnDemo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDemo);

        btnCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabasicexamples/ui/images/processing.png"))); // NOI18N
        btnCodigo.setToolTipText("Codigo");
        btnCodigo.setFocusable(false);
        btnCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCodigo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCodigo);

        PaneEjemplo.getContentContainer().add(jToolBar1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout panelDemoLayout = new javax.swing.GroupLayout(panelDemo);
        panelDemo.setLayout(panelDemoLayout);
        panelDemoLayout.setHorizontalGroup(
            panelDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        panelDemoLayout.setVerticalGroup(
            panelDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        PaneEjemplo.getContentContainer().add(panelDemo, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(PaneEjemplo);

        jXTaskPane1.setTitle("Ejemplos");

        jXHyperlink1.setText("Concatenar cadenas");
        jXTaskPaneContainer1.add(jXHyperlink1);

        jXTaskPane1.getContentPane().add(jXTaskPaneContainer1);

        jSplitPane1.setLeftComponent(jXTaskPane1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDemoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTitledPanel PaneEjemplo;
    private javax.swing.JToggleButton btnCodigo;
    private javax.swing.JToggleButton btnDemo;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.swingx.JXPanel panelDemo;
    // End of variables declaration//GEN-END:variables
}
